[package]
name = "gcode-thumbnailer"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
clap = { version = "4.6.1", features = ["derive"] }
env_logger = "0.11.10"
ere = "0.2.4"
# disable default features (alloc and serde) as we don't want them
gcode = { version = "0.7.0", default-features = false }
log = "0.4.29"
